Tue, 23 Feb 2016 17:17:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8181/ (Press CTRL+C to quit)
Tue, 23 Feb 2016 17:17:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:18:11 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\runserver.py', reloading
Tue, 23 Feb 2016 17:18:11 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:18:19 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Tue, 23 Feb 2016 17:18:19 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:18:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:18:25] "GET /servers HTTP/1.1" 404 -
Tue, 23 Feb 2016 17:19:16 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] ERROR 192.168.39.170 - - [23/Feb/2016 17:19:16] code 400, message Bad request syntax ('\xff\xf4\xff\xfd\x06')
Tue, 23 Feb 2016 17:19:16 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:19:16] "����" 400 -
Tue, 23 Feb 2016 17:19:55 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:19:55] "GET //servers HTTP/1.1" 404 -
Tue, 23 Feb 2016 17:20:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\__init__.py', reloading
Tue, 23 Feb 2016 17:20:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:20:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:20:08] "GET /aa/servers HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:20:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\__init__.py', reloading
Tue, 23 Feb 2016 17:20:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:20:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:20:30] "GET /v2/servers HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:20:55 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\__init__.py', reloading
Tue, 23 Feb 2016 17:20:55 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:21:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:21:01] "GET /v1/servers HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:21:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\__init__.py', reloading
Tue, 23 Feb 2016 17:21:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:21:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:21:18] "GET /servers HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:23:37 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:23:37 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:23:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:23:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:23:51 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:23:51 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:24:42 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:24:42 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:25:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:25:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:26:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:26:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:26:24 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:26:24 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:26:56 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:26:56 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:27:10 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:27:10 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:27:32 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:27:32 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:27:46 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:27:46] "GET /servers HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:28:01 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:28:02 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:28:03 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=305317552&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=ke4W5TWyvVSmOIWpbk6HfhUrbkA%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456219681&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:28:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:28:03] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 500 -
Tue, 23 Feb 2016 17:28:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:28:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:28:42 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:28:42 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:28:43 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1471991118&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=c4wpgTSkCA1ypTnZ1FpkB79kIDA%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456219722&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:28:43 E:\twocloud\tc_api\api\nova.py[line:59] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    return jsonify(result)
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:28:43 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:28:43] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:28:54 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:28:54 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:28:54 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=105591119&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=B7dAw4BO8vSByp5WZ1rgNjQg1Yk%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456219734&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:28:54 E:\twocloud\tc_api\api\nova.py[line:59] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    return jsonify(result)
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:28:54 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:28:54] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:29:10 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:29:10 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:29:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:29:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:29:16 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:29:16 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:29:18 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=2056948937&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=J%2FwVWUA2j3bSUziHHx21g1xX23c%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456219756&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:29:18 E:\twocloud\tc_api\api\nova.py[line:59] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 57, in servers
    return jsonify(result)
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:29:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:29:18] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:29:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:29:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:29:42 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:29:43 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:29:44 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1987109137&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=i0%2BKzF6r7j6CKX%2BuCoM4Rerj3Fw%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456219783&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:29:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:29:44] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 200 -
Tue, 23 Feb 2016 17:30:26 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:30:26 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:30:26 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:30:26 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:30:29 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:30:29 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:30:30 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=103796798&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=Hj1Rv%2Flox0BB7fc6FxOIXouPpC4%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456219829&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:30:30 E:\twocloud\tc_api\api\nova.py[line:58] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    return jsonify(result)
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:30:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:30:30] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:32:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:32:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:32:24 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:32:24 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:32:25 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1392775551&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=YM37lAb%2Fe7p66MnBZgGLMPJ1GYg%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456219944&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:32:25 E:\twocloud\tc_api\api\nova.py[line:59] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 57, in servers
    return jsonify(result)
  File "C:\Python27\lib\site-packages\flask-0.10.1-py2.7.egg\flask\json.py", line 237, in jsonify
    return current_app.response_class(dumps(dict(*args, **kwargs),
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:32:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:32:25] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:32:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:32:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:32:46 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:32:46 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:32:47 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=2066190010&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=G3jZi7Q0Q%2BYDgAhDN%2FhIWgKT36I%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456219966&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:32:47 E:\twocloud\tc_api\api\nova.py[line:58] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    return jsonify(dict(result))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:32:47 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.



7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:32:47] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -

Tue, 23 Feb 2016 17:33:26 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:33:26 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:33:26 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1704946316&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=z%2FQTOBd4hUnuLfhq11FLOEK9PlQ%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220006&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:33:26 E:\twocloud\tc_api\api\nova.py[line:58] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    return jsonify(dict(result))
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:33:26 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:33:26] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:33:47 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:33:47 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:33:53 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:33:53 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:33:54 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1813576092&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=qP77UqnAgQj0QsAWTOoN%2FkqHSFc%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220033&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:33:54 E:\twocloud\tc_api\api\nova.py[line:59] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    print dict(result)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:33:54 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:33:54] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:34:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:34:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:34:10 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:34:10 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:34:11 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1256947235&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=EVUlFq6kDtnhE1lJzcVvMaX22FY%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220050&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:34:11 E:\twocloud\tc_api\api\nova.py[line:58] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    print dict(result)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:34:11 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:34:11] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:34:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:34:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:34:32 E:\twocloud\tc_api\api\nova.py[line:41] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:34:32 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:34:33 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1204377429&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=vBYvx9uh8GXSJXNUp7CnVed6LpQ%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220072&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:34:33 E:\twocloud\tc_api\api\nova.py[line:59] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 57, in servers
    print dict(result)
ValueError: dictionary update sequence element #0 has length 1; 2 is required
Tue, 23 Feb 2016 17:34:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:34:33] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:35:36 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:35:36 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:35:38 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:35:39 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:35:40 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1351277583&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=x%2FGBPzuzsftthOzjM6nRH1PITRc%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220138&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:35:40 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:35:40] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 500 -
Tue, 23 Feb 2016 17:36:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:36:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:36:03 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:36:03 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:36:04 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=404759839&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=DSmbET46VpLYKrlQjzosVA81gO0%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220163&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:36:04 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:36:04] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 200 -
Tue, 23 Feb 2016 17:36:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:36:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:36:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:36:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:36:32 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:36:32 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Tue, 23 Feb 2016 17:36:33 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=970783396&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=BsaIFPJ9poMP1poN7hunTKaLgQg%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220192&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:36:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:36:33] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 200 -
Tue, 23 Feb 2016 17:36:42 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:36:42 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:36:43 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:36:43 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Tue, 23 Feb 2016 17:36:44 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1308498715&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=BVNyEnVGbbKk8L3NzrqXssJ%2B7RE%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220203&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:36:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:36:44] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 200 -
Tue, 23 Feb 2016 17:43:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:43:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:43:05 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:43:05 E:\twocloud\tc_api\api\nova.py[line:60] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    result = service.call(action, params)
  File "E:\twocloud\tc_api\api\third_party\QcloudApi\qcloudapi.py", line 83, in call
    service = self._factory(self.module, self.config)
  File "E:\twocloud\tc_api\api\third_party\QcloudApi\qcloudapi.py", line 62, in _factory
    raise ValueError , 'module not exists'
ValueError: module not exists
Tue, 23 Feb 2016 17:43:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:43:05] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:43:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:43:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:43:32 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:43:32 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): csec.api.qcloud.com
Tue, 23 Feb 2016 17:43:38 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1999662171&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=KPahkb2K8qcLTNNnqh%2Bo74WkuBQ%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220612&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:43:38 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:43:38] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 200 -
Tue, 23 Feb 2016 17:43:54 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:43:54 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:44:32 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:44:32 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:44:33 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:44:33 E:\twocloud\tc_api\api\nova.py[line:60] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    result = service.call(action, params)
  File "E:\twocloud\tc_api\api\third_party\QcloudApi\qcloudapi.py", line 83, in call
    service = self._factory(self.module, self.config)
  File "E:\twocloud\tc_api\api\third_party\QcloudApi\qcloudapi.py", line 18, in _factory
    service = Cvm(config)
  File "E:\twocloud\tc_api\api\third_party\QcloudApi\modules\base.py", line 21, in __init__
    self.defaultRegion = config['Region']
KeyError: 'Region'
Tue, 23 Feb 2016 17:44:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:44:33] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:44:39 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:44:39 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:44:44 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:44:44 E:\twocloud\tc_api\api\nova.py[line:60] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 56, in servers
    result = service.call(action, params)
  File "E:\twocloud\tc_api\api\third_party\QcloudApi\qcloudapi.py", line 83, in call
    service = self._factory(self.module, self.config)
  File "E:\twocloud\tc_api\api\third_party\QcloudApi\qcloudapi.py", line 18, in _factory
    service = Cvm(config)
  File "E:\twocloud\tc_api\api\third_party\QcloudApi\modules\base.py", line 21, in __init__
    self.defaultRegion = config['Region']
KeyError: 'Region'
Tue, 23 Feb 2016 17:44:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:44:44] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Tue, 23 Feb 2016 17:44:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 17:44:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 17:45:12 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 17:45:12 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Tue, 23 Feb 2016 17:45:13 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=835265296&RequestClient=SDK_PYTHON_1.1&Region=%E5%8C%BA%E5%9F%9F%E5%8F%82%E6%95%B0&Signature=1O5sF2FaGJGXcwcugaWrqktB4qo%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456220712&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 17:45:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 17:45:13] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 200 -
Tue, 23 Feb 2016 18:01:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 18:01:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 18:01:19 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 18:01:19 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Tue, 23 Feb 2016 18:01:21 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1241701321&RequestClient=SDK_PYTHON_1.1&Region=&Signature=4zZ4NLXVPsjAdg5AsK1QVfFEk3U%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456221679&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 18:01:21 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 18:01:21] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 200 -
Tue, 23 Feb 2016 18:02:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Tue, 23 Feb 2016 18:02:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 23 Feb 2016 18:02:10 E:\twocloud\tc_api\api\nova.py[line:42] INFO Request: get vm servers list tenant_id => 123 region => zhenru from => None to => None
Tue, 23 Feb 2016 18:02:10 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Tue, 23 Feb 2016 18:02:15 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=973533310&RequestClient=SDK_PYTHON_1.1&Region=gz&Signature=NtfUyzi5eY8gxZm6WXt8kw0QXQ4%3D&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456221730&Action=DescribeInstances HTTP/1.1" 200 None
Tue, 23 Feb 2016 18:02:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [23/Feb/2016 18:02:15] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 200 -
Wed, 24 Feb 2016 10:36:17 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 10:36:17 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 10:40:52 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 10:40:52 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 10:41:38 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 10:41:38 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 10:41:48 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 10:41:48 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 10:42:45 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 10:42:45 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 10:42:48 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 10:42:48] "GET /servers?tenant_id=123&region=zhenru HTTP/1.1" 400 -
Wed, 24 Feb 2016 10:43:02 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>zhenru from=>None to=>None
Wed, 24 Feb 2016 10:43:02 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 10:43:03 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1333607037&projectId=123&Region=zhenru&RequestClient=SDK_PYTHON_1.1&Signature=s9rkmWgfDt5bVRcYjuav4CyXc1U%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456281782 HTTP/1.1" 200 None
Wed, 24 Feb 2016 10:43:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 10:43:03] "GET /servers?party=qcloud&tenant_id=123&region=zhenru HTTP/1.1" 200 -
Wed, 24 Feb 2016 10:43:14 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>None to=>None
Wed, 24 Feb 2016 10:43:14 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 10:43:14 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1364877021&projectId=123&Region=gz&RequestClient=SDK_PYTHON_1.1&Signature=1GMBhg19ZFBZ1l%2BRnUcMm%2Fq4%2FCg%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456281794 HTTP/1.1" 200 None
Wed, 24 Feb 2016 10:43:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 10:43:14] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 10:47:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\config.py', reloading
Wed, 24 Feb 2016 10:47:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 10:49:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\config.py', reloading
Wed, 24 Feb 2016 10:49:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:23:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 11:23:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:26:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Wed, 24 Feb 2016 11:26:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:26:46 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>None to=>None
Wed, 24 Feb 2016 11:26:46 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 11:26:48 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=2076671846&projectId=123&Region=gz&RequestClient=SDK_PYTHON_1.1&Signature=POHtjWVVM5MeKlquM%2BUdTgdrZZI%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456284406 HTTP/1.1" 200 None
Wed, 24 Feb 2016 11:26:48 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 11:26:48] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 11:46:11 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 11:46:11 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:55:17 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 11:55:17 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:55:26 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>None to=>None
Wed, 24 Feb 2016 11:55:26 E:\twocloud\tc_api\api\nova.py[line:66] ERROR Error with get vm_servers
Traceback (most recent call last):
  File "E:\twocloud\tc_api\api\nova.py", line 62, in servers
    result = service.call(action, params)
  File "E:\twocloud\tc_api\api\api_util.py", line 45, in call
    _params = format_params(self.options['party'], params)
  File "E:\twocloud\tc_api\api\api_util.py", line 27, in format_params
    new_params[PARAMS[keys][party]] = params[keys]
KeyError: 't'
Wed, 24 Feb 2016 11:55:26 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 11:55:26] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 400 -
Wed, 24 Feb 2016 11:57:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 11:57:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:57:26 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>None to=>None
Wed, 24 Feb 2016 11:57:26 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 11:57:27 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=373282984&projectId=123&Region=gz&RequestClient=SDK_PYTHON_1.1&Signature=EZz7JJsDJ0x2QY3kZgomUckgdeE%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456286246 HTTP/1.1" 200 None
Wed, 24 Feb 2016 11:57:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 11:57:27] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 11:58:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 11:58:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:58:26 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>None to=>None
Wed, 24 Feb 2016 11:58:26 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 11:58:27 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1358257760&projectId=123&Region=gz&RequestClient=SDK_PYTHON_1.1&Signature=DQV74rHeFpXI%2FF8Q%2By%2FpV1HzTJ8%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456286306 HTTP/1.1" 200 None
Wed, 24 Feb 2016 11:58:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 11:58:27] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 11:59:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 11:59:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:59:23 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>None to=>None
Wed, 24 Feb 2016 11:59:23 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 11:59:24 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=369569566&projectId=123&Region=gz&RequestClient=SDK_PYTHON_1.1&Signature=T6OBuyIMRK4UmAio8UPm2rJSHqQ%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456286363 HTTP/1.1" 200 None
Wed, 24 Feb 2016 11:59:24 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 11:59:24] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 11:59:46 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 11:59:46 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 11:59:46 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>None to=>None
Wed, 24 Feb 2016 11:59:46 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 11:59:47 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=176736538&projectId=123&Region=gz&RequestClient=SDK_PYTHON_1.1&Signature=dNpIZMfS3wFoVPmsAS95SgGKC%2FI%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456286386 HTTP/1.1" 200 None
Wed, 24 Feb 2016 11:59:47 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 11:59:47] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 12:00:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:00:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:00:17 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>0 to=>None
Wed, 24 Feb 2016 12:00:18 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 12:00:19 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=518498129&projectId=123&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=IZ1SO%2BuZw9ySLl%2FZMaqp90FIbZM%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456286418 HTTP/1.1" 200 None
Wed, 24 Feb 2016 12:00:19 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 12:00:19] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 12:01:11 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:01:11 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:01:13 E:\twocloud\tc_api\api\nova.py[line:44] INFO Request: get vm servers list party=> qcloudtenant_id=>123 region=>gz from=>0 to=>None
Wed, 24 Feb 2016 12:01:13 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 12:01:14 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=805350722&Timestamp=1456286473&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=QLHkscaCwk9Bev6lFcTG7QzjeDY%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv HTTP/1.1" 200 None
Wed, 24 Feb 2016 12:01:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 12:01:14] "GET /servers?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 12:01:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:01:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:06:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 12:06:42 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:16:39 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:16:39 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:18:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:18:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:22:56 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:22:56 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:24:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:24:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:24:37 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:24:37 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:25:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 12:25:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:30:45 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 12:30:46 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:37:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Wed, 24 Feb 2016 12:37:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:41:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 12:41:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:41:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 12:41:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 12:50:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 12:50:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 14:37:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 14:37:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 14:52:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Wed, 24 Feb 2016 14:52:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 14:52:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 14:52:30] "GET /servers/act?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 405 -
Wed, 24 Feb 2016 14:52:38 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 14:52:38] "POST /servers/act?party=qcloud&tenant_id=123&region=gz HTTP/1.1" 400 -
Wed, 24 Feb 2016 14:54:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 14:54:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 14:57:20 E:\twocloud\tc_api\api\nova.py[line:98] INFO Request: execute pm action username=>liujiahua act=>on server_ids=>123446 tenant_id=>98765 region=>gz party=>qcloud 
Wed, 24 Feb 2016 14:57:20 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 14:57:22 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=776268214&Timestamp=1456297040&Region=gz&instanceIds.1=123446&RequestClient=SDK_PYTHON_1.1&Signature=aCeVJOIPYBKH47Tyt6omsq7iN9c%3D&Action=StartInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv HTTP/1.1" 200 None
Wed, 24 Feb 2016 14:57:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 14:57:22] "POST /servers/act HTTP/1.1" 200 -
Wed, 24 Feb 2016 14:57:55 E:\twocloud\tc_api\api\nova.py[line:98] INFO Request: execute pm action username=>liujiahua act=>on server_ids=>123446,1234567 tenant_id=>98765 region=>gz party=>qcloud 
Wed, 24 Feb 2016 14:57:55 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 14:57:55 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=7686740&Timestamp=1456297075&Region=gz&instanceIds.2=1234567&instanceIds.1=123446&RequestClient=SDK_PYTHON_1.1&Signature=ccDmU%2F1mbySU7QsZmybffsnQBsU%3D&Action=StartInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv HTTP/1.1" 200 None
Wed, 24 Feb 2016 14:57:55 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 14:57:55] "POST /servers/act HTTP/1.1" 200 -
Wed, 24 Feb 2016 14:58:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 14:58:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 14:58:16 E:\twocloud\tc_api\api\nova.py[line:98] INFO Request: execute pm action username=>liujiahua act=>on server_ids=>123446,1234567 tenant_id=>98765 region=>gz party=>qcloud 
Wed, 24 Feb 2016 14:58:16 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 14:58:17 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=802238668&Timestamp=1456297096&Region=gz&instanceIds.2=1234567&instanceIds.1=123446&RequestClient=SDK_PYTHON_1.1&Signature=CyIS%2BX2qlaFSyJyNvXMUf38tivw%3D&Action=StartInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv HTTP/1.1" 200 None
Wed, 24 Feb 2016 14:58:17 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 14:58:17] "POST /servers/act HTTP/1.1" 200 -
Wed, 24 Feb 2016 14:58:36 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 14:58:36 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 14:59:40 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Wed, 24 Feb 2016 14:59:40 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 15:04:59 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 15:04:59 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 15:06:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\api_util.py', reloading
Wed, 24 Feb 2016 15:06:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 15:06:27 E:\twocloud\tc_api\api\nova.py[line:98] INFO Request: execute pm action username=>liujiahua act=>on server_ids=>123446,1234567 tenant_id=>98765 region=>gz party=>qcloud 
Wed, 24 Feb 2016 15:06:27 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 15:06:28 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1901201335&Timestamp=1456297587&Region=gz&instanceIds.2=1234567&instanceIds.1=123446&RequestClient=SDK_PYTHON_1.1&Signature=g3nbs6e8315F0HtMdUeHLKYzG4k%3D&Action=StartInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv HTTP/1.1" 200 None
Wed, 24 Feb 2016 15:06:28 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 15:06:28] "POST /servers/act HTTP/1.1" 200 -
Wed, 24 Feb 2016 15:36:54 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\config.py', reloading
Wed, 24 Feb 2016 15:36:54 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 15:37:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\config.py', reloading
Wed, 24 Feb 2016 15:37:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 15:46:56 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\__init__.py', reloading
Wed, 24 Feb 2016 15:46:56 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 15:47:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 15:47:05] "POST //twocloud/servers/act HTTP/1.1" 404 -
Wed, 24 Feb 2016 15:47:11 E:\twocloud\tc_api\api\nova.py[line:98] INFO Request: execute pm action username=>liujiahua act=>on server_ids=>123446,1234567 tenant_id=>98765 region=>gz party=>qcloud 
Wed, 24 Feb 2016 15:47:11 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 15:47:12 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1858902862&Timestamp=1456300031&Region=gz&instanceIds.2=1234567&instanceIds.1=123446&RequestClient=SDK_PYTHON_1.1&Signature=LcTnf4C3tQX%2BLUPtCULOnRTNnmo%3D&Action=StartInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv HTTP/1.1" 200 None
Wed, 24 Feb 2016 15:47:12 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 15:47:12] "POST /twocloud/servers/act HTTP/1.1" 200 -
Wed, 24 Feb 2016 16:09:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\config.py', reloading
Wed, 24 Feb 2016 16:09:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 16:09:37 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\config.py', reloading
Wed, 24 Feb 2016 16:09:37 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 16:10:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 16:10:03] "GET /servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 404 -
Wed, 24 Feb 2016 16:10:11 E:\twocloud\tc_api\api\nova.py[line:45] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Wed, 24 Feb 2016 16:10:11 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 16:10:12 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1066848607&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=pC7jPpm%2F8gufVJYde3sBDFB0mHY%3D&Action=DescribeInstances&SecretId=AKIDhMsDLHasPm8MPMtqKcoskQ1TkogLk8EA&Timestamp=1456301411 HTTP/1.1" 200 None
Wed, 24 Feb 2016 16:10:12 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 16:10:12] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 200 -
Wed, 24 Feb 2016 16:18:09 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\config.py', reloading
Wed, 24 Feb 2016 16:18:09 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Wed, 24 Feb 2016 16:18:13 E:\twocloud\tc_api\api\nova.py[line:45] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Wed, 24 Feb 2016 16:18:13 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Wed, 24 Feb 2016 16:18:14 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1248982555&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=tGNaQCMVbOj%2Bm8srFXdzScY41BE%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456301893 HTTP/1.1" 200 None
Wed, 24 Feb 2016 16:18:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [24/Feb/2016 16:18:14] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 200 -
Thu, 25 Feb 2016 14:24:08 E:\twocloud\tc_api\api\nova.py[line:45] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Thu, 25 Feb 2016 14:24:08 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Thu, 25 Feb 2016 14:24:08 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=988871617&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=Ua%2F%2B7lXG07biU0CdtrJoAjroyxY%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456381448 HTTP/1.1" 200 None
Thu, 25 Feb 2016 14:24:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 14:24:08] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 200 -
Thu, 25 Feb 2016 14:31:12 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Thu, 25 Feb 2016 14:31:12 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 14:35:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Thu, 25 Feb 2016 14:35:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 14:35:02 E:\twocloud\tc_api\api\nova.py[line:48] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Thu, 25 Feb 2016 14:35:02 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Thu, 25 Feb 2016 14:35:03 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=523775753&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=8vkpfXamxGeEwa6o5vpbJ3h5Pj4%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456382102 HTTP/1.1" 200 None
Thu, 25 Feb 2016 14:35:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 14:35:03] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 200 -
Thu, 25 Feb 2016 14:36:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Thu, 25 Feb 2016 14:36:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 15:37:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Thu, 25 Feb 2016 15:37:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 15:37:20 E:\twocloud\tc_api\api\nova.py[line:48] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Thu, 25 Feb 2016 15:37:20 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Thu, 25 Feb 2016 15:37:21 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1987397602&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=7Tej8ZuOmp6lJn%2Ftc7gc6c%2FKcOg%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456385840 HTTP/1.1" 200 None
Thu, 25 Feb 2016 15:37:21 E:\twocloud\tc_api\api\utils\api_util.py[line:28] INFO Qcloud response: {"code":4000,"message":"\u8bf7\u6c42\u5931\u8d25\uff0c\u53c2\u6570\u9519\u8bef:[projectId]"}
Thu, 25 Feb 2016 15:37:21 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 15:37:21] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 200 -
Thu, 25 Feb 2016 15:38:05 E:\twocloud\tc_api\api\nova.py[line:48] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Thu, 25 Feb 2016 15:38:05 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Thu, 25 Feb 2016 15:38:05 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1033023990&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=F9SLPmp%2FemZbasnHcVj1lgBHqvA%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456385885 HTTP/1.1" 200 None
Thu, 25 Feb 2016 15:38:05 E:\twocloud\tc_api\api\utils\api_util.py[line:28] INFO Qcloud response: {"code":4000,"message":"\u8bf7\u6c42\u5931\u8d25\uff0c\u53c2\u6570\u9519\u8bef:[projectId]"}
Thu, 25 Feb 2016 15:38:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 15:38:05] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 200 -
Thu, 25 Feb 2016 15:41:04 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Thu, 25 Feb 2016 15:41:04 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 15:41:06 E:\twocloud\tc_api\api\nova.py[line:48] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Thu, 25 Feb 2016 15:41:06 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Thu, 25 Feb 2016 15:41:08 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1175329849&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=OElxMizN9XTutDiPFYBl16xbe68%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456386066 HTTP/1.1" 200 None
Thu, 25 Feb 2016 15:41:08 E:\twocloud\tc_api\api\utils\api_util.py[line:28] INFO Qcloud response: {"code":4000,"message":"\u8bf7\u6c42\u5931\u8d25\uff0c\u53c2\u6570\u9519\u8bef:[projectId]"}
Thu, 25 Feb 2016 15:41:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 15:41:08] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 400 -
Thu, 25 Feb 2016 15:41:40 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Thu, 25 Feb 2016 15:41:40 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 15:41:56 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 15:41:56] "POST //twocloud/servers/act HTTP/1.1" 404 -
Thu, 25 Feb 2016 15:42:04 E:\twocloud\tc_api\api\nova.py[line:103] INFO Request: execute pm action username=>liujiahua act=>on server_ids=>123446,1234567 tenant_id=>98765 region=>gz party=>qcloud 
Thu, 25 Feb 2016 15:42:04 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Thu, 25 Feb 2016 15:42:06 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=756479475&Timestamp=1456386124&Region=gz&instanceIds.2=1234567&instanceIds.1=123446&RequestClient=SDK_PYTHON_1.1&Signature=D5yY2hW%2FehhSJLc3eb6f128t%2BJw%3D&Action=StartInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv HTTP/1.1" 200 None
Thu, 25 Feb 2016 15:42:06 E:\twocloud\tc_api\api\utils\api_util.py[line:28] INFO Qcloud response: {"code":4000,"message":"\u8d44\u6e90\u4e0d\u5b58\u5728:[instanceIds]\u3002"}
Thu, 25 Feb 2016 15:42:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 15:42:06] "POST /twocloud/servers/act HTTP/1.1" 400 -
Thu, 25 Feb 2016 15:43:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Thu, 25 Feb 2016 15:43:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 15:48:36 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Thu, 25 Feb 2016 15:48:36 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 15:49:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Thu, 25 Feb 2016 15:49:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 15:53:28 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Thu, 25 Feb 2016 15:53:28 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 15:56:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Thu, 25 Feb 2016 15:56:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 16:03:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Thu, 25 Feb 2016 16:03:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:01:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\models.py', reloading
Thu, 25 Feb 2016 17:01:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:01:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\models.py', reloading
Thu, 25 Feb 2016 17:01:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:10:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000300A228>
Thu, 25 Feb 2016 17:10:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:10:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:10:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Thu, 25 Feb 2016 17:10:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:10:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FFD228>
Thu, 25 Feb 2016 17:10:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:10:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:23:58 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\nova.py', reloading
Thu, 25 Feb 2016 17:23:58 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:23:58 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000304D228>
Thu, 25 Feb 2016 17:23:58 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:23:58 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:25:51 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\__init__.py', reloading
Thu, 25 Feb 2016 17:25:51 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:36:34 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030FF228>
Thu, 25 Feb 2016 17:36:34 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:36:34 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:37:46 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000003099228>
Thu, 25 Feb 2016 17:37:46 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:37:46 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:37:46 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Thu, 25 Feb 2016 17:37:46 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:37:46 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000003006228>
Thu, 25 Feb 2016 17:37:46 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:37:46 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:38:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:38:00] "GET /twocloud/tokens HTTP/1.1" 404 -
Thu, 25 Feb 2016 17:38:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:38:06] "POST /twocloud/tokens HTTP/1.1" 404 -
Thu, 25 Feb 2016 17:38:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\__init__.py', reloading
Thu, 25 Feb 2016 17:38:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:38:41 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FE6228>
Thu, 25 Feb 2016 17:38:41 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:38:41 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:38:45 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:38:45] "POST /twocloud/tokens HTTP/1.1" 500 -
Thu, 25 Feb 2016 17:40:04 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 17:40:04 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 17:40:05 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000305E228>
Thu, 25 Feb 2016 17:40:05 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:40:05 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:40:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:40:13] "POST /twocloud/tokens HTTP/1.1" 500 -
Thu, 25 Feb 2016 17:43:41 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002F8D288>
Thu, 25 Feb 2016 17:43:41 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:43:41 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:45:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:45:05] "POST /twocloud/tokens HTTP/1.1" 500 -
Thu, 25 Feb 2016 17:45:40 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000309D288>
Thu, 25 Feb 2016 17:45:40 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:45:40 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 17:46:12 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:46:12] "POST /twocloud/tokens HTTP/1.1" 401 -
Thu, 25 Feb 2016 17:47:01 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:47:01] "POST /twocloud/tokens HTTP/1.1" 401 -
Thu, 25 Feb 2016 17:47:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:47:22] "POST /twocloud/tokens HTTP/1.1" 401 -
Thu, 25 Feb 2016 17:48:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 17:48:14] "POST /twocloud/tokens HTTP/1.1" 401 -
Thu, 25 Feb 2016 18:02:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 18:02:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 18:02:07 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000308F228>
Thu, 25 Feb 2016 18:02:07 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:02:07 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:02:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 18:02:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 18:02:27 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000303F228>
Thu, 25 Feb 2016 18:02:27 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:02:27 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:03:13 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Thu, 25 Feb 2016 18:03:13 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Thu, 25 Feb 2016 18:03:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:03:14] "POST /twocloud/users HTTP/1.1" 500 -
Thu, 25 Feb 2016 18:04:10 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:04:10] "POST /twocloud/users HTTP/1.1" 400 -
Thu, 25 Feb 2016 18:04:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:04:15] "POST /twocloud/users HTTP/1.1" 400 -
Thu, 25 Feb 2016 18:05:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:05:05] "POST /twocloud/users HTTP/1.1" 400 -
Thu, 25 Feb 2016 18:05:13 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FEA228>
Thu, 25 Feb 2016 18:05:13 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:05:13 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:05:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Thu, 25 Feb 2016 18:05:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 18:05:13 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030CF228>
Thu, 25 Feb 2016 18:05:13 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:05:13 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:05:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 18:05:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 18:05:29 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000310F228>
Thu, 25 Feb 2016 18:05:29 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:05:29 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:05:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:05:33] "POST /twocloud/users HTTP/1.1" 400 -
Thu, 25 Feb 2016 18:05:45 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:05:45] "POST /twocloud/tokens HTTP/1.1" 401 -
Thu, 25 Feb 2016 18:05:55 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:05:55] "POST /twocloud/users HTTP/1.1" 400 -
Thu, 25 Feb 2016 18:06:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:06:18] "POST /twocloud/users HTTP/1.1" 500 -
Thu, 25 Feb 2016 18:06:40 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:06:40] "POST /twocloud/users HTTP/1.1" 400 -
Thu, 25 Feb 2016 18:07:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 18:07:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 18:07:00 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030EF228>
Thu, 25 Feb 2016 18:07:00 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:07:00 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:07:05 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:07:05] "POST /twocloud/users HTTP/1.1" 400 -
Thu, 25 Feb 2016 18:07:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 18:07:20 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 18:07:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000316F228>
Thu, 25 Feb 2016 18:07:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:07:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:08:18 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Thu, 25 Feb 2016 18:08:18 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Thu, 25 Feb 2016 18:08:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:08:18] "POST /twocloud/tokens HTTP/1.1" 500 -
Thu, 25 Feb 2016 18:08:51 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\models.py', reloading
Thu, 25 Feb 2016 18:08:51 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 18:08:51 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000312F228>
Thu, 25 Feb 2016 18:08:51 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:08:51 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:09:11 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000310D288>
Thu, 25 Feb 2016 18:09:11 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:09:11 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 18:09:38 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Thu, 25 Feb 2016 18:09:38 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Thu, 25 Feb 2016 18:09:39 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:09:39] "POST /twocloud/users HTTP/1.1" 500 -
Thu, 25 Feb 2016 18:10:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 18:10:08] "POST /twocloud/tokens HTTP/1.1" 500 -
Thu, 25 Feb 2016 19:49:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 19:49:08 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 19:49:09 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FAF228>
Thu, 25 Feb 2016 19:49:09 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:49:09 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:49:16 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Thu, 25 Feb 2016 19:49:16 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Thu, 25 Feb 2016 19:49:17 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:49:17] "POST /twocloud/tokens HTTP/1.1" 200 -
Thu, 25 Feb 2016 19:52:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:52:23] "POST /twocloud/users HTTP/1.1" 500 -
Thu, 25 Feb 2016 19:53:52 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 19:53:52 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 19:53:53 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030EF228>
Thu, 25 Feb 2016 19:53:53 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:53:53 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:54:24 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Thu, 25 Feb 2016 19:54:24 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Thu, 25 Feb 2016 19:54:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:54:25] "POST /twocloud/users HTTP/1.1" 200 -
Thu, 25 Feb 2016 19:54:38 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 19:54:38 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 19:54:38 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FAF228>
Thu, 25 Feb 2016 19:54:38 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:54:38 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:55:58 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Thu, 25 Feb 2016 19:55:58 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Thu, 25 Feb 2016 19:55:59 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:55:59] "POST /twocloud/tokens HTTP/1.1" 200 -
Thu, 25 Feb 2016 19:56:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:56:29] "POST /twocloud/tokens HTTP/1.1" 200 -
Thu, 25 Feb 2016 19:57:19 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 19:57:19 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 19:57:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FDF228>
Thu, 25 Feb 2016 19:57:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:57:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:57:58 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:57:58] "POST /twocloud/resource HTTP/1.1" 405 -
Thu, 25 Feb 2016 19:58:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:58:00] "POST /twocloud/resources HTTP/1.1" 404 -
Thu, 25 Feb 2016 19:58:19 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 19:58:19 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 19:58:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FAF228>
Thu, 25 Feb 2016 19:58:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:58:20 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 19:58:25 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:58:25] "GET /twocloud/resources HTTP/1.1" 404 -
Thu, 25 Feb 2016 19:58:27 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:58:27] "GET /twocloud/resource HTTP/1.1" 200 -
Thu, 25 Feb 2016 19:58:54 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:58:54] "GET /twocloud/resource HTTP/1.1" 401 -
Thu, 25 Feb 2016 19:58:59 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 19:58:59] "GET /twocloud/resource HTTP/1.1" 200 -
Thu, 25 Feb 2016 20:00:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 20:00:15 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 20:00:15 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030CF228>
Thu, 25 Feb 2016 20:00:15 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:00:15 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:00:21 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 20:00:21] "GET /twocloud/resource HTTP/1.1" 200 -
Thu, 25 Feb 2016 20:01:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 20:01:29 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 20:01:29 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000311F228>
Thu, 25 Feb 2016 20:01:29 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:01:29 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:01:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 20:01:30] "GET /twocloud/resource HTTP/1.1" 200 -
Thu, 25 Feb 2016 20:01:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 20:01:44 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 20:01:44 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FCF228>
Thu, 25 Feb 2016 20:01:44 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:01:44 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:01:45 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 20:01:45] "GET /twocloud/resource HTTP/1.1" 200 -
Thu, 25 Feb 2016 20:04:13 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 20:04:13] "GET /twocloud/resource HTTP/1.1" 401 -
Thu, 25 Feb 2016 20:09:21 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Thu, 25 Feb 2016 20:09:21 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Thu, 25 Feb 2016 20:09:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 20:09:22] "GET /twocloud/resource HTTP/1.1" 401 -
Thu, 25 Feb 2016 20:10:47 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 20:10:47] "GET /twocloud/resource HTTP/1.1" 200 -
Thu, 25 Feb 2016 20:11:55 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [25/Feb/2016 20:11:55] "GET /twocloud/resource HTTP/1.1" 200 -
Thu, 25 Feb 2016 20:12:53 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 20:12:53 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 20:12:54 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000302F228>
Thu, 25 Feb 2016 20:12:54 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:12:54 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:13:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 20:13:31 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 20:13:31 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030BF228>
Thu, 25 Feb 2016 20:13:31 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:13:31 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:14:46 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Thu, 25 Feb 2016 20:14:46 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Thu, 25 Feb 2016 20:14:47 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FFF228>
Thu, 25 Feb 2016 20:14:47 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Thu, 25 Feb 2016 20:14:47 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:30:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 10:30:30 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:30:30 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FFD228>
Fri, 26 Feb 2016 10:30:30 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:30:30 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:30:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:30:41] "GET /twocloud/resource HTTP/1.1" 401 -
Fri, 26 Feb 2016 10:30:48 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Fri, 26 Feb 2016 10:30:48 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Fri, 26 Feb 2016 10:30:49 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:30:49] "GET /twocloud/resource HTTP/1.1" 200 -
Fri, 26 Feb 2016 10:30:52 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:30:52] "GET /twocloud/resource HTTP/1.1" 401 -
Fri, 26 Feb 2016 10:30:58 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:30:58] "GET /twocloud/resource HTTP/1.1" 200 -
Fri, 26 Feb 2016 10:31:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 10:31:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:31:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000306A228>
Fri, 26 Feb 2016 10:31:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:31:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:32:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:32:06] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 401 -
Fri, 26 Feb 2016 10:32:21 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Fri, 26 Feb 2016 10:32:21 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Fri, 26 Feb 2016 10:32:22 E:\twocloud\tc_api\api\nova.py[line:45] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Fri, 26 Feb 2016 10:32:22 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Fri, 26 Feb 2016 10:32:24 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1714053532&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=jW3NI7F2d3WSDUyCPds7tJ0yAYE%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456453942 HTTP/1.1" 200 None
Fri, 26 Feb 2016 10:32:24 E:\twocloud\tc_api\api\utils\api_util.py[line:28] INFO Qcloud response: {"code":4000,"message":"\u8bf7\u6c42\u5931\u8d25\uff0c\u53c2\u6570\u9519\u8bef:[projectId]"}
Fri, 26 Feb 2016 10:32:24 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:32:24] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 400 -
Fri, 26 Feb 2016 10:33:00 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:33:00] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 401 -
Fri, 26 Feb 2016 10:41:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 10:41:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:41:33 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030BA228>
Fri, 26 Feb 2016 10:41:33 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:41:33 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:43:43 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 10:43:43 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:43:44 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000307A228>
Fri, 26 Feb 2016 10:43:44 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:43:44 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:44:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 10:44:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:44:03 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000300A228>
Fri, 26 Feb 2016 10:44:03 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:44:03 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:49:07 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Fri, 26 Feb 2016 10:49:07 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:49:07 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000301A228>
Fri, 26 Feb 2016 10:49:07 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:49:07 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:49:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Fri, 26 Feb 2016 10:49:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:49:22 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FFA228>
Fri, 26 Feb 2016 10:49:22 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:49:22 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:49:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Fri, 26 Feb 2016 10:49:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:49:33 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FBA228>
Fri, 26 Feb 2016 10:49:33 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:49:33 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:51:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 10:51:23 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:51:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000307A228>
Fri, 26 Feb 2016 10:51:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:51:23 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:52:26 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Fri, 26 Feb 2016 10:52:26 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:52:26 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000308A228>
Fri, 26 Feb 2016 10:52:26 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:52:26 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:53:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Fri, 26 Feb 2016 10:53:03 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:53:03 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000308A228>
Fri, 26 Feb 2016 10:53:03 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:53:03 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:53:09 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\common.py', reloading
Fri, 26 Feb 2016 10:53:09 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:53:09 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000301A228>
Fri, 26 Feb 2016 10:53:09 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:53:09 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:56:04 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 10:56:04 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:56:04 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000309A228>
Fri, 26 Feb 2016 10:56:04 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:56:04 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:57:09 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\utils\\api_util.py', reloading
Fri, 26 Feb 2016 10:57:09 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 10:57:10 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000304A228>
Fri, 26 Feb 2016 10:57:10 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:57:10 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 10:57:53 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Fri, 26 Feb 2016 10:57:53 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Fri, 26 Feb 2016 10:57:54 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:57:54] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 10:58:57 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:58:57] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 10:59:34 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 10:59:34] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:00:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:00:33] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:01:22 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:01:22] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 401 -
Fri, 26 Feb 2016 11:01:30 E:\twocloud\tc_api\api\nova.py[line:45] INFO Request: get vm servers list party=> qcloudtenant_id=>1002777 region=>gz from=>0 to=>None
Fri, 26 Feb 2016 11:01:30 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Fri, 26 Feb 2016 11:01:35 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=123243371&projectId=1002777&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=OzyZ7UIfmv0nJsvIqJfJ6f%2FAXyc%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456455690 HTTP/1.1" 200 None
Fri, 26 Feb 2016 11:01:35 E:\twocloud\tc_api\api\utils\api_util.py[line:30] INFO Qcloud response: {"code":4000,"message":"\u8bf7\u6c42\u5931\u8d25\uff0c\u53c2\u6570\u9519\u8bef:[projectId]"}
Fri, 26 Feb 2016 11:01:35 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:01:35] "GET /twocloud/servers?party=qcloud&tenant_id=1002777&region=gz HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:01:50 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:01:50] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:02:04 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:02:04] "POST /twocloud/add_tenant HTTP/1.1" 401 -
Fri, 26 Feb 2016 11:02:35 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 11:02:35 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 11:02:36 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000307A228>
Fri, 26 Feb 2016 11:02:36 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:02:36 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:02:40 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Fri, 26 Feb 2016 11:02:40 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Fri, 26 Feb 2016 11:02:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:02:41] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:02:49 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:02:49] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:03:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 11:03:14 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 11:03:14 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FFA228>
Fri, 26 Feb 2016 11:03:14 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:03:14 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:03:17 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Fri, 26 Feb 2016 11:03:17 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Fri, 26 Feb 2016 11:03:18 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:03:18] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:03:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 11:03:33 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 11:03:34 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FEA228>
Fri, 26 Feb 2016 11:03:34 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:03:34 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:04:06 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x0000000002FB5228>
Fri, 26 Feb 2016 11:04:06 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:04:06 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:04:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Running on http://0.0.0.0:8282/ (Press CTRL+C to quit)
Fri, 26 Feb 2016 11:04:06 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 11:04:06 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030CA228>
Fri, 26 Feb 2016 11:04:06 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:04:06 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 11:04:11 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha512_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha512_crypt'>
Fri, 26 Feb 2016 11:04:11 C:\Python27\lib\site-packages\passlib\registry.py[line:284] DEBUG registered 'sha256_crypt' handler: <class 'passlib.handlers.sha2_crypt.sha256_crypt'>
Fri, 26 Feb 2016 11:04:12 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:04:12] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:04:52 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:04:52] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:05:00 E:\twocloud\tc_api\api\identity.py[line:68] INFO Request: get vm servers list party=> qcloudtenant_name=>test tenant_desc=>test region=>gz 
Fri, 26 Feb 2016 11:05:00 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): account.api.qcloud.com
Fri, 26 Feb 2016 11:05:02 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=589831304&projectName=test&Region=gz&projectDesc=test&RequestClient=SDK_PYTHON_1.1&Signature=9YpB%2BCVVIpvS%2FgvTZFbon5JbgYU%3D&Action=AddProject&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456455900 HTTP/1.1" 200 None
Fri, 26 Feb 2016 11:05:02 E:\twocloud\tc_api\api\utils\api_util.py[line:30] INFO Qcloud response: {"code":0,"message":"","projectId":1005655}
Fri, 26 Feb 2016 11:05:02 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:05:02] "POST /twocloud/add_tenant HTTP/1.1" 200 -
Fri, 26 Feb 2016 11:06:36 E:\twocloud\tc_api\api\identity.py[line:68] INFO Request: get vm servers list party=> qcloudtenant_name=>test tenant_desc=>test region=>gz 
Fri, 26 Feb 2016 11:06:36 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): account.api.qcloud.com
Fri, 26 Feb 2016 11:06:36 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=683550883&projectName=test&Region=gz&projectDesc=test&RequestClient=SDK_PYTHON_1.1&Signature=VTKhtUX4bHnpD4jcJRr2gAgfu7o%3D&Action=AddProject&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456455996 HTTP/1.1" 200 None
Fri, 26 Feb 2016 11:06:36 E:\twocloud\tc_api\api\utils\api_util.py[line:30] INFO Qcloud response: {"code":5100,"message":"(11308)\u670d\u52a1\u5185\u90e8\u9519\u8bef\u3002"}
Fri, 26 Feb 2016 11:06:36 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:06:36] "POST /twocloud/add_tenant HTTP/1.1" 400 -
Fri, 26 Feb 2016 11:13:40 E:\twocloud\tc_api\api\nova.py[line:45] INFO Request: get vm servers list party=> qcloudtenant_id=>1005655 region=>gz from=>0 to=>None
Fri, 26 Feb 2016 11:13:40 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:735] INFO Starting new HTTPS connection (1): cvm.api.qcloud.com
Fri, 26 Feb 2016 11:13:41 C:\Python27\lib\site-packages\requests\packages\urllib3\connectionpool.py[line:383] DEBUG "GET /v2/index.php?Nonce=1604656717&projectId=1005655&Region=gz&offset=0&RequestClient=SDK_PYTHON_1.1&Signature=seWm9N3bvmVdTdamdMs7qd0IZbQ%3D&Action=DescribeInstances&SecretId=AKIDngzxODvMrt3ae7LAm171fnLpHF0ymyuv&Timestamp=1456456420 HTTP/1.1" 200 None
Fri, 26 Feb 2016 11:13:41 E:\twocloud\tc_api\api\utils\api_util.py[line:30] INFO Qcloud response: {"totalCount":0,"instanceSet":[],"code":0,"message":""}
Fri, 26 Feb 2016 11:13:41 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO 192.168.39.170 - - [26/Feb/2016 11:13:41] "GET /twocloud/servers?party=qcloud&tenant_id=1005655&region=gz HTTP/1.1" 200 -
Fri, 26 Feb 2016 15:53:26 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 15:53:26 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 15:53:26 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x00000000030CA228>
Fri, 26 Feb 2016 15:53:26 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 15:53:26 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Fri, 26 Feb 2016 16:06:31 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\api\\identity.py', reloading
Fri, 26 Feb 2016 16:06:31 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Fri, 26 Feb 2016 16:06:32 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000300A228>
Fri, 26 Feb 2016 16:06:32 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Fri, 26 Feb 2016 16:06:32 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
Tue, 01 Mar 2016 15:18:24 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Detected change in 'E:\\twocloud\\tc_api\\config.py', reloading
Tue, 01 Mar 2016 15:18:24 C:\Python27\lib\site-packages\werkzeug-0.10.4-py2.7.egg\werkzeug\_internal.py[line:87] INFO  * Restarting with stat
Tue, 01 Mar 2016 15:18:25 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'SafeConfigParser': <class ConfigParser.SafeConfigParser at 0x000000000319A228>
Tue, 01 Mar 2016 15:18:25 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'NativeStringIO': <built-in function StringIO>
Tue, 01 Mar 2016 15:18:25 C:\Python27\lib\site-packages\passlib\utils\compat.py[line:413] DEBUG loaded lazy attr 'BytesIO': <built-in function StringIO>
